https://www.tensorflow.org/tutorials/structured_data/time_series

In [2]:

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical


In [16]:
# должны быть четные числа:
window_size = 30
shift=4

def create_sliding_window(X, y, window_size, shift=1):
    """
    Создает набор данных с окнами, скользящими по временному ряду.
    
    Аргументы:
    X - временной ряд
    window_size - размер окна
    shift - сдвиг окна
    
    Возвращает временной массив с окнами,
    массив с метками для каждого окна
    """
    
    dataset, labels = [], []
    
    for i in range(0, len(X) - window_size, shift):
        X_window = X[i:(i + window_size)]
        dataset.append(X_window)
    
        y_window = y[i:(i + window_size)]
        max_label = np.argmax(np.bincount(y_window, minlength=3))
        labels.append(max_label)
    
    return np.array(dataset), np.array(labels)


In [3]:
early_stop = EarlyStopping(monitor='val_loss', patience=5)

In [ ]:
#ЭКСГАУСТЕР №4

In [4]:
X_columns = [
       'ЭКСГАУСТЕР 4. ТОК РОТОРА 1', 'ЭКСГАУСТЕР 4. ТОК РОТОРА2',
       'ЭКСГАУСТЕР 4. ТОК СТАТОРА', 'ЭКСГАУСТЕР 4. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ',
       'ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 1',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 2',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4',
       'ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.']

In [5]:
y_columns = [
    'Y_ЭКСГАУСТЕР А/М №4_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_УЛИТА ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ЭЛЕКТРОАППАРАТУРА ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ №2 ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ЗАДВИЖКА ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ГСМ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ.№4 Т.1',
    'Y_ЭКСГАУСТЕР А/М №4_ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1',
    'Y_ЭКСГАУСТЕР А/М №4_РОТОР ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_МАСЛООХЛАДИТЕЛЬ  М-05-1 ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ЭКСГАУСТЕР А/М №4',
    'Y_ЭКСГАУСТЕР А/М №4_ЗАП. И РЕГ. АРМАТУРА ЭКСГ.№4',
    'Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ №1 ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_КЛ1 ТР№4 ДО ЭД ЭКСГАУСТЕРА №4',
    'Y_ЭКСГАУСТЕР А/М №4_КЛ2 ТР№4 ДО ЭД ЭКСГАУСТЕРА №4',
    'Y_ЭКСГАУСТЕР А/М №4_ТР-Р ТМ-4000-10/6 ЭКСГ. №4',
    'Y_ЭКСГАУСТЕР А/М №4_ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ЭКСГ4 ВУ1',
    'Y_ЭКСГАУСТЕР А/М №4_МАСЛОПРОВОДЫ ЭКСГ №4'
]

In [6]:
df = pd.read_parquet('../data/X_train.parquet', columns=X_columns)

In [8]:
df.isna().sum() / df.shape[0]

ЭКСГАУСТЕР 4. ТОК РОТОРА 1                         0.089145
ЭКСГАУСТЕР 4. ТОК РОТОРА2                          0.089787
ЭКСГАУСТЕР 4. ТОК СТАТОРА                          0.050400
ЭКСГАУСТЕР 4. ДАВЛЕНИЕ МАСЛА В СИСТЕМЕ             0.074934
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 1    0.311692
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 2    0.322731
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 3    0.318135
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА ПОДШИПНИКА НА ОПОРЕ 4    0.312509
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В СИСТЕМЕ          0.317008
ЭКСГАУСТЕР 4. ТЕМПЕРАТУРА МАСЛА В МАСЛОБЛОКЕ       0.322672
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 1                  0.085936
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 2                  0.099344
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3                  0.087411
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 3. ПРОДОЛЬНАЯ.     0.051190
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4                  0.044901
ЭКСГАУСТЕР 4. ВИБРАЦИЯ НА ОПОРЕ 4. ПРОДОЛЬНАЯ.     0.089594
dtype: float64

In [7]:
dfi = df.interpolate()

In [8]:
dfi.isna().sum().sum()

0

In [8]:
y = pd.read_parquet('../data/y_train.parquet', columns=y_columns)

In [22]:
y

Y_ЭКСГАУСТЕР А/М №4_ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ. №4   
DT                                                                                 
2019-01-16 13:21:00                                                0.0            \
2019-01-16 13:21:10                                                0.0             
2019-01-16 13:21:20                                                0.0             
2019-01-16 13:21:30                                                0.0             
2019-01-16 13:21:40                                                0.0             
...                                                                ...             
2021-12-31 23:59:10                                                2.0             
2021-12-31 23:59:20                                                2.0             
2021-12-31 23:59:30                                                2.0             
2021-12-31 23:59:40                                                2.0             
2021-12-31 23:59:50                                                2.0             

                     Y_ЭКСГАУСТЕР А/М №4_ПОДШИПНИК ОПОРНЫЙ ЭКСГ. №4   
DT                                                                    
2019-01-16 13:21:00                                             0.0  \
2019-01-16 13:21:10                                             0.0   
2019-01-16 13:21:20                                             0.0   
2019-01-16 13:21:30                                             0.0   
2019-01-16 13:21:40                                             0.0   
...                                                             ...   
2021-12-31 23:59:10                                             2.0   
2021-12-31 23:59:20                                             2.0   
2021-12-31 23:59:30                                             2.0   
2021-12-31 23:59:40                                             2.0   
2021-12-31 23:59:50                                             2.0   

                     Y_ЭКСГАУСТЕР А/М №4_УЛИТА ЭКСГ. №4   
DT                                                        
2019-01-16 13:21:00                                 0.0  \
2019-01-16 13:21:10                                 0.0   
2019-01-16 13:21:20                                 0.0   
2019-01-16 13:21:30                                 0.0   
2019-01-16 13:21:40                                 0.0   
...                                                 ...   
2021-12-31 23:59:10                                 2.0   
2021-12-31 23:59:20                                 2.0   
2021-12-31 23:59:30                                 2.0   
2021-12-31 23:59:40                                 2.0   
2021-12-31 23:59:50                                 2.0   

                     Y_ЭКСГАУСТЕР А/М №4_РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ. №4   
DT                                                                         
2019-01-16 13:21:00                                                0.0    \
2019-01-16 13:21:10                                                0.0     
2019-01-16 13:21:20                                                0.0     
2019-01-16 13:21:30                                                0.0     
2019-01-16 13:21:40                                                0.0     
...                                                                ...     
2021-12-31 23:59:10                                                0.0     
2021-12-31 23:59:20                                                0.0     
2021-12-31 23:59:30                                                0.0     
2021-12-31 23:59:40                                                0.0     
2021-12-31 23:59:50                                                0.0     

                     Y_ЭКСГАУСТЕР А/М №4_МАСЛОНАСОС РАБОЧИЙ ЭКСГ. №4   
DT                                                                     
2019-01-16 13:21:00                                              0.0  \
2019-01-16 13:21:10            

In [9]:
y = y.iloc[:,5]
print(dfi.shape)
print(y.shape)

(9335034, 16)
(9335034,)


In [10]:
y.unique()

array([0., 1., 2.])

In [31]:
y.isna().sum()

0

In [11]:

# Масштабирование
scaler = MinMaxScaler()
dfi_norm = scaler.fit_transform(np.array(dfi).reshape(-1, 1)).flatten()


In [12]:

X_train = dfi_norm[:3000000]
y_train = y[0:3000000]

X_val = dfi_norm[3000000:3500000]
y_val = y[3000000:3500000]


In [17]:

# Создаем набор данных с окнами
X_train_window, y_train_window = create_sliding_window(X_train, y_train, window_size, shift=shift)
X_val_window, y_val_window = create_sliding_window(X_val, y_val, window_size, shift=shift)

print(X_train_window.shape)
print(y_train_window.shape)

# Кодирование
y_train_encoded = to_categorical(y_train_window, num_classes=3)
y_val_encoded = to_categorical(y_val_window, num_classes=3)

# Преобразуем в формат TensorFlow
X_train_window = tf.convert_to_tensor(X_train_window)
y_train_window = tf.convert_to_tensor(y_train_encoded)
X_val_window = tf.convert_to_tensor(X_val_window)
y_val_window = tf.convert_to_tensor(y_val_encoded)

print('После преобразования в формат TensorFlow:')
print(X_train_window.shape)
print(y_train_window.shape)
print(X_val_window.shape)
print(y_val_window.shape)


(749993, 30)
(749993,)
После преобразования в формат TensorFlow:
(749993, 30)
(749993, 3)
(124993, 30)
(124993, 3)


In [13]:
# Модель
model = tf.keras.Sequential([
    layers.Conv1D(32, kernel_size=5, activation='relu', input_shape=(window_size, 1)),
    layers.Conv1D(32, kernel_size=5, activation='relu', input_shape=(window_size, 1)),
    layers.MaxPooling1D(pool_size=3),
    layers.LSTM(64),    # return_sequences, return_state
    layers.Dropout(0.2),
    layers.Dense(64),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 26, 32)            192       
                                                                 
 conv1d_1 (Conv1D)           (None, 22, 32)            5152      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 7, 32)            0         
 )                                                               
                                                                 
 lstm (LSTM)                 (None, 64)                24832     
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 64)                4160      
                                                        

In [16]:

# Обучение
history = model.fit(X_train_window, y_train_window,
                    epochs=50,
                    shuffle=False,
                    validation_split=0.2,
                    callbacks=[early_stop])


Epoch 1/50
18750/18750 [==============================] - 130s 7ms/step - loss: 0.0015 - accuracy: 0.9999 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 2/50
18750/18750 [==============================] - 126s 7ms/step - loss: 4.8240e-04 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 3/50
18750/18750 [==============================] - 126s 7ms/step - loss: 5.3075e-04 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 4/50
18750/18750 [==============================] - 127s 7ms/step - loss: 5.3581e-04 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/50
18750/18750 [==============================] - 123s 7ms/step - loss: 5.0211e-04 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 6/50
18750/18750 [==============================] - 129s 7ms/step - loss: 4.8126e-04 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000


In [16]:
tf.keras.models.save_model(model, '../models/ex4_X_all_y_5')

NameError: name 'model' is not defined

In [17]:
# Оценка по окнам
_, accuracy = model.evaluate(X_val_window, y_val_window)
print("Accuracy:", accuracy)


3907/3907 [==============================] - 10s 3ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Accuracy: 1.0


In [19]:

y_pred_window = model.predict(X_val_window)
print(y_pred_window.shape)

# округление вероятности + декодирование (по индексам столбцов)
y_pred_window = np.argmax(y_pred_window, axis=1)  
print(y_pred_window.shape)


3907/3907 [==============================] - 9s 2ms/step
(124993, 3)
(124993,)


In [57]:
np.unique(y_pred_window)  # тестовая выборка была без аварий

array([0], dtype=int64)

In [59]:
y_val.unique()

array([0.])

In [61]:
y_train.unique()  # тренировочная выборка была только с авариями с простоем M1=1

array([0., 1.])

In [20]:
def restore_labels(y_window):
    """
    Восстанавливает массив меток исходной размерности из массива с окнами.
    Значению присваивается метка из первого окна последовательности.
    
    """
    labels = []
    
    labels.extend([y_window[0]] * (window_size - shift))
    
    for i in range(len(y_window)):
        labels.extend([y_window[i]] * shift)

    return np.array(labels)

In [22]:
y_pred = restore_labels(y_pred_window)
y_pred

(499998,)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
print(y_pred.shape)   # :)
print(y_val.shape)

(499998,)
(500000,)


In [31]:
len(y_pred) - len(y_val)

-2

In [32]:
# Оценка без окон

accuracy = accuracy_score(y_val[:(len(y_pred) - len(y_val))], y_pred)
accuracy

1.0

In [48]:

to_file = np.column_stack(y_val[:(len(y_pred) - len(y_val))], y_pred) 

pd.DataFrame(to_file).to_csv('../results/ex4_X_all_y_5.csv')


3907/3907 [==============================] - 10s 3ms/step
